'use strict';

/**
 * Markdown 報告產生器
 * 輸入：autocannon 結果物件
 * 輸出：.md 檔案
 */

const fs = require('fs');

function generateMdReport(result, outputPath) {
  const {
    title = '負載測試報告',
    start,
    finish,
    duration,
    connections,
    requests,
    latency,
    throughput,
    errors,
    non2xx,
    timeouts,
  } = result;

  const startTime = start ? new Date(start).toLocaleString('zh-TW') : '-';
  const endTime   = finish ? new Date(finish).toLocaleString('zh-TW') : '-';
  const totalReqs = requests?.total ?? 0;
  const reqPerSec = requests?.average ?? 0;
  const errCount  = (errors ?? 0) + (non2xx ?? 0) + (timeouts ?? 0);
  const errRate   = totalReqs > 0 ? ((errCount / totalReqs) * 100).toFixed(2) : '0.00';

  const p99       = latency?.p99 ?? 0;
  const passP99   = p99 < 1000;
  const passErr   = parseFloat(errRate) < 5;

  const badge = (pass) => pass ? '✅ PASS' : '❌ FAIL';

  const md = `# ${title}

> 產生時間：${new Date().toLocaleString('zh-TW')}
> 測試區間：${startTime} ~ ${endTime}

---

## 概覽

| 項目 | 數值 |
|------|------|
| 總請求數 | ${totalReqs.toLocaleString()} req |
| 平均 RPS | ${Math.round(reqPerSec).toLocaleString()} req/s |
| 並發連線 | ${connections ?? '-'} conn |
| 測試時長 | ${duration ?? '-'} sec |

---

## 延遲分佈（Latency）

| 指標 | 數值 |
|------|------|
| min | ${latency?.min ?? '-'} ms |
| mean（平均） | ${typeof latency?.mean === 'number' ? latency.mean.toFixed(1) : '-'} ms |
| p50（中位數） | ${latency?.p50 ?? '-'} ms |
| p75 | ${latency?.p75 ?? '-'} ms |
| p90 | ${latency?.p90 ?? '-'} ms |
| p99 | ${latency?.p99 ?? '-'} ms |
| max | ${latency?.max ?? '-'} ms |
| stddev | ${typeof latency?.stddev === 'number' ? latency.stddev.toFixed(1) : '-'} ms |

---

## 請求統計

| 項目 | 數值 |
|------|------|
| 總請求數 | ${totalReqs.toLocaleString()} req |
| 平均 RPS | ${Math.round(reqPerSec).toLocaleString()} req/s |
| 吞吐量（平均） | ${throughput?.average ? (throughput.average / 1024).toFixed(1) : '-'} KB/s |
| 錯誤總數（non-2xx + timeout） | ${errCount} |
| 錯誤率 | ${errRate} % |
| Non-2xx 回應 | ${non2xx ?? 0} |
| Timeouts | ${timeouts ?? 0} |

---

## 閾值判斷

| 閾值 | 標準 | 實際值 | 結果 |
|------|------|--------|------|
| p99 延遲 | < 1000 ms | ${p99} ms | ${badge(passP99)} |
| 錯誤率 | < 5% | ${errRate} % | ${badge(passErr)} |

---

*Generated by autocannon + custom reporter*
`;

  fs.writeFileSync(outputPath, md, 'utf8');
}

module.exports = { generateMdReport };
